# Generated by Django 5.1.7 on 2025-03-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('button_text', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
            ],
        ),
    ]
