# Generated by Django 5.1.6 on 2025-03-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_remove_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=2055, null=True),
        ),
    ]
