# Generated by Django 5.2 on 2025-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
