# Generated by Django 5.1.6 on 2025-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('cost', models.FloatField()),
                ('booker_name', models.CharField(blank=True, max_length=150, null=True)),
                ('booker_email', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
