# Generated by Django 5.1.6 on 2025-03-11 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('application', 'Application Letter'), ('internship', 'Internship Request'), ('recommendation', 'Recommendation Request'), ('leave', 'Leave Application'), ('permission', 'Permission Letter'), ('custom', 'Custom Letter')], max_length=20)),
                ('template_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
