# Generated by Django 5.2 on 2025-04-16 09:47

# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations

# --- Define the data for your templates ---
# --- YOU MUST ENSURE THE form_structure and pdf_structure ARE CORRECT FOR YOUR TEMPLATES ---
INITIAL_TEMPLATES = [
    {
        "name": "Internship Request",
        "template_type": "internship", # Unique identifier
        "description": "Template for requesting an internship position.",
        "color_class": "yellow", # Choose appropriate color class
        "form_structure": {
            # Example structure - REPLACE/VERIFY WITH YOURS
            "fields": [
                {"name": "yourName", "label": "Your Full Name", "type": "text", "required": True},
                {"name": "yourEmail", "label": "Your Email Address", "type": "email", "required": True},
                {"name": "yourDegree", "label": "Degree Program", "type": "text", "required": True},
                {"name": "yourDepartment", "label": "Department", "type": "text", "required": True},
                {"name": "yourSemester", "label": "Current Semester", "type": "number", "required": True},
                {"name": "companyName", "label": "Company Name", "type": "text", "required": True},
                {"name": "Position", "label": "Position Applied For", "type": "text", "required": True},
                {"name": "startDate", "label": "Internship Start Date", "type": "date", "required": True},
                {"name": "endDate", "label": "Internship End Date", "type": "date", "required": True},
                {"name": "Date", "label": "Date of Letter", "type": "date", "required": True}
            ]
        },
        "pdf_structure": {
            # Example structure - REPLACE/VERIFY WITH YOURS
           "elements": [
                {"type": "paragraph", "field": "Date", "style": "Normal", "alignment": "RIGHT"},
                {"type": "spacer", "size": 0.2},
                {"type": "paragraph", "text": "To,", "style": "Normal"},
                {"type": "paragraph", "text": "The HR Manager,", "style": "Normal"},
                {"type": "paragraph", "field": "companyName", "style": "Normal"},
                {"type": "spacer", "size": 0.3},
                {"type": "paragraph", "text": "Subject: Application for Internship Position", "style": "Heading3"},
                {"type": "spacer", "size": 0.2},
                {"type": "paragraph", "text": "Dear Sir/Ma'am,", "style": "Normal"},
                {"type": "spacer", "size": 0.1},
                {"type": "paragraph",
                 "template": "I am {yourName}, a student pursuing {yourDegree} in {yourDepartment} (Semester {yourSemester}). I wish to apply for the {Position} internship at {companyName}, starting from {startDate} to {endDate}. I am eager to gain practical experience and believe I can contribute positively. My resume is attached for your review. Thank you for your consideration.",
                 "style": "Normal"},
                {"type": "spacer", "size": 0.3},
                {"type": "paragraph", "text": "Yours sincerely,", "style": "Normal"},
                {"type": "spacer", "size": 0.3},
                {"type": "paragraph", "field": "yourName", "style": "Normal"}
            ]
        },
        "validation_schema": {
            "type": "object",
            "required": ["yourName", "yourEmail", "yourDegree", "yourDepartment", "yourSemester", "companyName", "Position", "startDate", "endDate"],
            "properties":{
                "yourName":{"type":"string", "minLength": 1,"pattern":"^[a-zA-Z ]+$"},
                "yourEmail":{"type":"string", "format":"email"},
                "yourDegree":{"type":"string", "minLength": 2,"pattern":"^[a-zA-Z ]+$"},
                "yourDepartment":{"type":"string", "minLength": 3,"pattern":"^[a-zA-Z ]+$"},
                "yourSemester":{"type":"integer", "minimum": 1},
                "companyName":{"type":"string", "minLength": 2,"pattern":"^[a-zA-Z ]+$"},
                "Position":{"type":"string", "minLength": 2,"pattern":"^[a-zA-Z ]+$"},
                "startDate":{"type":"string", "format":"date"},
                "endDate":{"type":"string", "format":"date"},
                "Date":{"type":"string", "format":"date"}
            },
            "allOf": [
                {
                    "if": {
                        "properties": { "startDate": { "type": "string" }, "endDate": { "type": "string" } },
                        "required": ["startDate", "endDate"]
                    },
                    "then": {
                        "dependencies": {
                            "endDate": {
                                "properties": {
                                    "endDate": { 
                                        "formatMinimum": { "$data": "1/startDate" }
                                    }
                                }
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": { "startDate": { "type": "string" }, "Date": { "type": "string" } },
                        "required": ["startDate", "Date"]
                    },
                    "then": {
                        "properties": {
                            "startDate": { 
                                "formatMinimum": { "$data": "1/Date" }
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": { "endDate": { "type": "string" }, "Date": { "type": "string" } },
                        "required": ["endDate", "Date"]
                    },
                    "then": {
                        "properties": {
                            "endDate": { 
                                "formatMinimum": { "$data": "1/Date" }
                            }
                        }
                    }
                }
            ]
        } # Optional: Define if needed
    },
    {
        "name": "Duty Leave Application",
        "template_type": "dutyleave", # Unique identifier
        "description": "Template for applying for duty leave for events.",
        "color_class": "green", # Choose appropriate color class
        # --- YOU MUST MANUALLY DEFINE/VERIFY THIS ---
        "form_structure": {
            # Replace/Verify with your actual Duty Leave form structure JSON
             "fields": [
                {"name": "yourName", "label": "Your Name", "type": "text", "required": True},
                {"name": "yourEmail", "label": "Your Email", "type": "email", "required": True},
                {"name": "yourDegree", "label": "Degree Program", "type": "text", "required": True},
                {"name": "yourDepartment", "label": "Department", "type": "text", "required": True},
                {"name": "yourSemester", "label": "Semester", "type": "number", "required": True},
                {"name": "yourRollno", "label": "Your Roll Number", "type": "text", "required": True},
                {"name": "eventName", "label": "Event Name", "type": "text", "required": True},
                {"name": "eventHolder", "label": "Event Organizer", "type": "text", "required": True},
                {"name": "eventVenue", "label": "Event Venue", "type": "text", "required": True},
                {"name": "eventDate", "label": "Event Date", "type": "date", "required": True},
                {"name": "startTime", "label": "Start Time", "type": "time", "required": True},
                {"name": "endTime", "label": "End Time", "type": "time", "required": True},
                {"name": "eventDescription", "label": "Event Description", "type": "textarea", "required": False},
                {"name": "studentDetails", "label": "Student Details (other students if applicable)", "type": "textarea", "required": False},
                {"name": "Date", "label": "Current Date", "type": "date", "required": True}
             ]
        },
        # --- YOU MUST MANUALLY DEFINE/VERIFY THIS ---
        "pdf_structure": {
            # Replace/Verify with your actual Duty Leave PDF structure JSON
             "elements": [
                 {"type": "paragraph", "field": "Date", "style": "Normal", "alignment": "RIGHT"},
                 {"type": "spacer", "size": 0.2},
                 {"type": "paragraph", "text": "To,", "style": "Normal"},
                 {"type": "paragraph", "text": "The Head of Department,", "style": "Normal"},
                 {"type": "paragraph", "field": "yourDepartment", "style": "Normal"},
                 {"type": "spacer", "size": 0.3},
                 {"type": "paragraph", "text": "Subject: Application for Duty Leave", "style": "Heading3"},
                 {"type": "spacer", "size": 0.2},
                 {"type": "paragraph", "text": "Respected Sir/Madam,", "style": "Normal"},
                 {"type": "spacer", "size": 0.1},
                 {"type": "paragraph",
                  "template": "I, {yourName} (Roll No: {yourRollno}), student of {yourDegree} ({yourSemester} Semester, {yourDepartment}), request duty leave on {eventDate} from {startTime} to {endTime} to participate in the event \"{eventName}\" organized by {eventHolder} at {eventVenue}. The event details are as follows: {eventDescription}. I assure you I will cover any missed work. Thank you.",
                  "style": "Normal"},
                 {"type": "spacer", "size": 0.3},
                 {"type": "paragraph", "text": "Yours sincerely,", "style": "Normal"},
                 {"type": "spacer", "size": 0.3},
                 {"type": "paragraph", "field": "yourName", "style": "Normal"}
             ]
        },
        "validation_schema": {
            "type": "object",
            "required": ["yourName", "yourEmail", "yourDegree", "yourDepartment", "yourSemester", 
                         "yourRollno", "eventName", "eventHolder", "eventVenue", "eventDate", 
                         "startTime", "endTime", "Date"],
            "properties": {
                "yourName": {"type": "string", "minLength": 1, "pattern": "^[a-zA-Z ]+$"},
                "yourEmail": {"type": "string", "format": "email"},
                "yourDegree": {"type": "string", "minLength": 2, "pattern": "^[a-zA-Z ]+$"},
                "yourDepartment": {"type": "string", "minLength": 3, "pattern": "^[a-zA-Z ]+$"},
                "yourSemester": {"type": "integer", "minimum": 1},
                "yourRollno": {"type": "string", "minLength": 1, "pattern": "^[A-Z0-9]+$"},
                "eventName": {"type": "string", "minLength": 2},
                "eventHolder": {"type": "string", "minLength": 2},
                "eventVenue": {"type": "string", "minLength": 2},
                "eventDate": {"type": "string", "format": "date"},
                "startTime": {"type": "string", "format": "time"},
                "endTime": {"type": "string", "format": "time"},
                "eventDescription": {"type": "string", "minLength": 10},
                "studentDetails": {"type": "string"}, # Optional field
                "Date": {"type": "string", "format": "date"}
            },
            "allOf": [
                {
                    "if": {
                        "properties": { "eventDate": { "type": "string" }, "Date": { "type": "string" } },
                        "required": ["eventDate", "Date"]
                    },
                    "then": {
                        "properties": {
                            "eventDate": { 
                                "formatMinimum": { "$data": "1/Date" }
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": { "startTime": { "type": "string" }, "endTime": { "type": "string" } },
                        "required": ["startTime", "endTime"]
                    },
                    "then": {
                        "dependencies": {
                            "endTime": {
                                "properties": {
                                    "endTime": { 
                                        "formatExclusiveMinimum": { "$data": "1/startTime" }
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        }
    },
     {
        "name": "Permission Letter",
        "template_type": "permission", # Unique identifier
        "description": "Template for requesting permission for special events or activities.",
        "color_class": "red", # Choose appropriate color class
        # --- YOU MUST MANUALLY DEFINE/VERIFY THIS ---
        "form_structure": {
             "fields": [
                {"name": "yourName", "label": "Your Name", "type": "text", "required": True},
                {"name": "yourEmail", "label": "Your Email", "type": "email", "required": True},
                {"name": "yourDegree", "label": "Degree Program", "type": "text", "required": True},
                {"name": "yourDepartment", "label": "Department", "type": "text", "required": True},
                {"name": "yourSemester", "label": "Semester", "type": "number", "required": True},
                {"name": "yourRollno", "label": "Your Roll Number", "type": "text", "required": True},
                {"name": "eventName", "label": "Event Name/Purpose", "type": "text", "required": True},
                {"name": "eventHolder", "label": "Event Organizer (if applicable)", "type": "text", "required": False},
                {"name": "eventVenue", "label": "Event Venue", "type": "text", "required": True},
                {"name": "eventDate", "label": "Event Date", "type": "date", "required": True},
                {"name": "eventDescription", "label": "Reason/Description for Permission", "type": "textarea", "required": True},
                {"name": "studentDetails", "label": "Student Details (other students if applicable)", "type": "textarea", "required": False},
                {"name": "recipientName", "label": "Recipient Name (e.g., Principal, Dean)", "type": "text", "required": True},
                {"name": "recipientTitle", "label": "Recipient Title", "type": "text", "required": True},
                {"name": "Date", "label": "Current Date", "type": "date", "required": True}
             ]
        },
        # --- YOU MUST MANUALLY DEFINE/VERIFY THIS ---
        "pdf_structure": {
             "elements": [
                 {"type": "paragraph", "field": "Date", "style": "Normal", "alignment": "RIGHT"},
                 {"type": "spacer", "size": 0.2},
                 {"type": "paragraph", "text": "To,", "style": "Normal"},
                 {"type": "paragraph", "field": "recipientTitle", "style": "Normal"}, # e.g., The Principal
                 {"type": "paragraph", "field": "recipientName", "style": "Normal"}, # e.g., Dr. John Smith
                 # {"type": "paragraph", "text": "College Name,", "style": "Normal"}, # Add if needed
                 {"type": "spacer", "size": 0.3},
                 {"type": "paragraph", "text": "Subject: Request for Permission - {eventName}", "style": "Heading3"}, # Insert event name in subject
                 {"type": "spacer", "size": 0.2},
                 {"type": "paragraph", "text": "Respected Sir/Madam,", "style": "Normal"},
                 {"type": "spacer", "size": 0.1},
                 {"type": "paragraph",
                  "template": "I, {yourName} (Roll No: {yourRollno}), student of {yourDegree} ({yourSemester} Semester, {yourDepartment}), am writing to request permission for the following: {eventDescription}. This pertains to the event/activity \"{eventName}\" to be held at {eventVenue} on {eventDate}. Details of other participating students: {studentDetails}. We assure you all rules will be adhered to.",
                  "style": "Normal"},
                 {"type": "spacer", "size": 0.2},
                 {"type": "paragraph", "text": "We kindly request your approval for this activity and would be grateful for your consideration.", "style": "Normal"},
                 {"type": "spacer", "size": 0.3},
                 {"type": "paragraph", "text": "Yours respectfully,", "style": "Normal"},
                 {"type": "spacer", "size": 0.3},
                 {"type": "paragraph", "field": "yourName", "style": "Normal"}
             ]
        },
        "validation_schema": {
            "type": "object",
            "required": ["yourName", "yourEmail", "yourDegree", "yourDepartment", "yourSemester", 
                         "yourRollno", "eventName", "eventVenue", "eventDate", 
                         "eventDescription", "recipientName", "recipientTitle", "Date"],
            "properties": {
                "yourName": {"type": "string", "minLength": 1, "pattern": "^[a-zA-Z ]+$"},
                "yourEmail": {"type": "string", "format": "email"},
                "yourDegree": {"type": "string", "minLength": 2, "pattern": "^[a-zA-Z ]+$"},
                "yourDepartment": {"type": "string", "minLength": 3, "pattern": "^[a-zA-Z ]+$"},
                "yourSemester": {"type": "integer", "minimum": 1},
                "yourRollno": {"type": "string", "minLength": 1, "pattern": "^[A-Z0-9]+$"},
                "eventName": {"type": "string", "minLength": 2},
                "eventHolder": {"type": "string"}, # Optional field
                "eventVenue": {"type": "string", "minLength": 2},
                "eventDate": {"type": "string", "format": "date"},
                "eventDescription": {"type": "string", "minLength": 10},
                "studentDetails": {"type": "string"}, # Optional field
                "recipientName": {"type": "string", "minLength": 2, "pattern": "^[a-zA-Z. ]+$"},
                "recipientTitle": {"type": "string", "minLength": 2},
                "Date": {"type": "string", "format": "date"}
            },
            "allOf": [
                {
                    "if": {
                        "properties": { "eventDate": { "type": "string" }, "Date": { "type": "string" } },
                        "required": ["eventDate", "Date"]
                    },
                    "then": {
                        "properties": {
                            "eventDate": { 
                                "formatMinimum": { "$data": "1/Date" }
                            }
                        }
                    }
                }
            ]
        }
    }
    # --- Add more template dictionaries here for others like 'recommendation', 'application', 'custom' ---
    # --- Make sure 'template_type' is unique for each ---
]


def populate_templates(apps, schema_editor):
    """
    Populates the LetterTemplate table with initial data defined above.
    """
    LetterTemplate = apps.get_model('letters', 'LetterTemplate')
    db_alias = schema_editor.connection.alias

    for template_data in INITIAL_TEMPLATES:
        # Check if structures are defined before trying to access them fully
        form_struct = template_data.get("form_structure")
        pdf_struct = template_data.get("pdf_structure")
        val_schema = template_data.get("validation_schema")

        if not form_struct or not pdf_struct:
             print(f"WARNING: Skipping template '{template_data.get('name', 'UNKNOWN')}' due to missing form or pdf structure definition.")
             continue # Skip if essential structures aren't defined

        LetterTemplate.objects.using(db_alias).update_or_create(
            template_type=template_data["template_type"],
            defaults={
                "name": template_data["name"],
                "description": template_data.get("description", ""),
                "color_class": template_data.get("color_class", "blue"), # Ensure this field exists in your model
                "form_structure": form_struct, # Assign the defined dict
                "pdf_structure": pdf_struct,   # Assign the defined dict
                "validation_schema": val_schema, # Assign the defined dict or None
            }
        )
        print(f"Processed template: {template_data['name']}")


def reverse_code(apps, schema_editor):
    """
    Deletes the templates created by this migration.
    """
    LetterTemplate = apps.get_model('letters', 'LetterTemplate')
    db_alias = schema_editor.connection.alias
    template_types = [t["template_type"] for t in INITIAL_TEMPLATES]
    LetterTemplate.objects.using(db_alias).filter(template_type__in=template_types).delete()
    print(f"Deleted initial templates: {template_types}")


class Migration(migrations.Migration):

    # This should depend on your initial migration (the one that creates the tables)
    dependencies = [
        ('letters', '0001_initial'), # Make sure this matches your new initial migration filename
    ]

    operations = [
        migrations.RunPython(populate_templates, reverse_code=reverse_code),
    ]